# questions.py

questions = [
    {"text": "1. How do you feel when you wake up?", "options": [("Energetic 🌞", 2), ("Okay 😐", 1), ("Tired 😴", -1)]},
    {"text": "2. How was your breakfast?", "options": [("Tasty 😋", 2), ("Okay 🥣", 1), ("Skipped it ❌", -2)]},
    {"text": "3. How do you feel about your current workload?", "options": [("Motivated 💪", 2), ("Neutral 🤷", 1), ("Overwhelmed 😓", -2)]},
    {"text": "4. Do you enjoy talking to people today?", "options": [("Yes 😄", 2), ("A little 🤏", 1), ("No 🙁", -1)]},
    {"text": "5. Did you get any fresh air today?", "options": [("Yes 🌳", 2), ("No ❌", -1), ("Just a little 🚪", 1)]},
    {"text": "6. Are you feeling appreciated today?", "options": [("Yes 💖", 2), ("Not sure 🤔", 0), ("Not really 😕", -1)]},
    {"text": "7. Do you feel anxious right now?", "options": [("No 😌", 2), ("A bit 😟", -1), ("Yes 😰", -2)]},
    {"text": "8. How are your energy levels?", "options": [("High ⚡", 2), ("Normal 😐", 1), ("Low 🪫", -2)]},
    {"text": "9. How did your last conversation make you feel?", "options": [("Happy 🥰", 2), ("Indifferent 😐", 0), ("Drained 😩", -2)]},
    {"text": "10. Do you feel lonely today?", "options": [("Not at all 😃", 2), ("Sometimes 😶", -1), ("Yes 😞", -2)]},
    {"text": "11. How well are you managing stress?", "options": [("Doing well 🧘", 2), ("Trying my best 🤞", 1), ("Struggling 😖", -2)]},
    {"text": "12. Do you feel in control of your day?", "options": [("Yes ✅", 2), ("Partly ⚖️", 1), ("No ❌", -1)]},
    {"text": "13. Are you excited about anything?", "options": [("Yes! 🎉", 2), ("Maybe 🤷", 0), ("Nothing 😔", -2)]},
    {"text": "14. How often are you smiling today?", "options": [("A lot 😁", 2), ("A little 🙂", 1), ("Not at all 🙃", -1)]},
    {"text": "15. How productive were you?", "options": [("Very 🚀", 2), ("So-so 📋", 1), ("Not at all 😓", -2)]},
    {"text": "16. How often do you feel bored?", "options": [("Rarely 🎨", 2), ("Sometimes 🕒", 1), ("Frequently 😵‍💫", -2)]},
    {"text": "17. How much screen time today?", "options": [("Less than 4 hrs ⏱️", 2), ("4-7 hrs 🖥️", 1), ("More than 7 hrs 😵", -1)]},
    {"text": "18. Did you do any physical activity?", "options": [("Yes 🏃", 2), ("A bit 🚶", 1), ("No 🪑", -1)]},
    {"text": "19. What’s your current emotion?", "options": [("Joy 😄", 2), ("Calm 😌", 1), ("Anger 😡", -2)]},
    {"text": "20. How's your focus?", "options": [("Sharp 🎯", 2), ("Okay 🤓", 1), ("Distracted 🙄", -1)]},
    {"text": "21. Did you compliment anyone today?", "options": [("Yes 🫶", 2), ("No 🙅", 0), ("Wasn't in the mood 😐", -1)]},
    {"text": "22. Did you eat something healthy?", "options": [("Yes 🥗", 2), ("A bit 🍌", 1), ("No 🍟", -1)]},
    {"text": "23. How’s your self-esteem today?", "options": [("High 😎", 2), ("Okay 🙂", 1), ("Low 😟", -1)]},
    {"text": "24. How do you feel about your future?", "options": [("Hopeful 🌈", 2), ("Uncertain 🤔", 0), ("Worried 😥", -2)]},
    {"text": "25. Did you spend time on hobbies?", "options": [("Yes 🎸", 2), ("A little ✏️", 1), ("No 🛌", -1)]},
    {"text": "26. How do you feel about your appearance?", "options": [("Confident 💅", 2), ("Okay 👕", 1), ("Insecure 😟", -2)]},
    {"text": "27. Did you help someone today?", "options": [("Yes 💌", 2), ("Not really 🤷", 0), ("No 🙈", -1)]},
    {"text": "28. How are your relationships today?", "options": [("Great 💞", 2), ("Okay 👋", 1), ("Tense 😬", -1)]},
    {"text": "29. What’s your stress level?", "options": [("Low 🧘", 2), ("Manageable 😅", 1), ("High 😖", -2)]},
    {"text": "30. Overall, how are you feeling now?", "options": [("Fantastic 🤩", 3), ("Okay 🙂", 1), ("Not good 😔", -2)]},
]
